### ISSUE TITLE
Course vs Lecture naming

### ISSUE THREAD

**Issue by jakub-tucek** [jakub-tucek/fit-checker#18]

**Comment by jakub-tucek** [comment]
Current state: both naming is present which is unfortunate.
Which will we use? And refactor rest?
I think We should pick option will be more easy to refactor.

**Comment by jakub-tucek** [comment]
In *.swift
- Course (whole word) - 25 matches in 8 files
- Lecture (whole word) - 35 matches in 8 files 
- Lecture - 124 
- Course - 120

**Comment by josefdolezal** [comment]
Hah, just made the same statistic. We should definitely pick one and keep it as convention. I used `Course` instead of `Lecture` because this convention is used on Edux.

If we move to Lecture, we should also rename parser objects and save short names (as Lecture) for model objects instead.

I also asked my friend who is native speaker about his opinion. So lets wait we will decide later..

**Comment by jakub-tucek** [comment]
Decided to use Course instead of Lecture. I will do refactor.

**Comment by jakub-tucek** [comment]
Changes in Feature/lecture-rename-course  branch
